import Patient from "./PatientsDB.js";
import mongooseDbConnect from "../config/dbConnect.js";
mongooseDbConnect();

function generateStudentID() {
  let studentID = "63025"; // นำค่าเริ่มต้นของรหัสนักศึกษาเข้ามาก่อน
  for (let i = 0; i < 5; i++) {
    // เพิ่มตัวเลขสุ่ม 5 ตัวเข้าไปในรหัสนักศึกษา
    studentID += Math.floor(Math.random() * 10); // สุ่มตัวเลขจาก 0 ถึง 9
  }
  return studentID;
}

const names = [
  "สมชาย",
  "สมหญิง",
  "สุขใจ",
  "สุดหล่อ",
  "สุดสวย",
  "สิริรัตน์",
  "สุรชัย",
  "สมหมาย",
  "สมปอง",
  "สมพร",
];

const lname = [
  "ทองมา",
  "เงินเมือง",
  "สวัสดี",
  "เพชรพระราม",
  "ชมพูนุที",
  "บาทหลวง",
  "ลิงน้อย",
  "ดาวเงิน",
  "น้ำตาลมะขาม",
  "จันทร์เงิน",
];

const organizations = [
  "คณะวิทยาศาสตร์และเทคโนโลยี",
  "คณะศิลปกรรมศาสตร์",
  "คณะสังคมสงเคราะห์ศาสตร์",
  "คณะนิติศาสตร์",
  "วิทยาลัยสหวิทยาการ",
  "คณะนิติศาสตร์",
];

function randomName() {
  // เลือกสุ่มชื่อจากรายการ
  const randomIndex = Math.floor(Math.random() * names.length);
  return names[randomIndex];
}

function randomllName() {
  // เลือกสุ่มชื่อจากรายการ
  const randomIndex = Math.floor(Math.random() * lname.length);
  return lname[randomIndex];
}

function randomorganizations() {
  // เลือกสุ่มชื่อจากรายการ
  const randomIndex = Math.floor(Math.random() * organizations.length);
  return organizations[randomIndex];
}

var patients = [
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },

  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
  {
    student_id: generateStudentID(),
    patient_fname: randomName(),
    patient_lname: randomllName(),
    status: "นักศึกษา",
    organizations: randomorganizations(),
    birthday: "2001-01-01",
    email: "ronaldo@gmail.com",
    phonenumber: "08921014785",

    allergy_medicine: "",
    allergy_medicine_detail: "",
    allergy_food: "",
    allergy_food_detail: "",
    smoking_status: "",
    smoking_status_detail: "",
    alcohol_consumption: "",
    alcohol_consumption_detail: "",
    other_substance: "",
    other_substance_detail: "",
    weight: "",
    height: "",
    body_temperature: "",
    heart_rate: "",
    respiratory_rate: "",
    blood_pressure: "",
    Last_edited: "",
    edited_by: "",
  },
];

//console.log(JSON.stringify(products));
Patient.insertMany(patients)
  .then(function (docs) {
    console.log("Successfully insert to DB");
    docs.forEach((e) => console.log(JSON.stringify(e, null, "\t")));
    console.log("done!!");
    process.kill(process.pid, "SIGINT");
  })
  .catch(function (err) {
    console.log(err);
  });
